### ISSUE TITLE
CI failures: include_what_you_use, projectroot.cpplint, header_guard

### ISSUE THREAD

**Issue by jhurliman** [ros-tooling/rosbag2_storage_mcap#30] opened 2022-04-20 20:20 UTC
https://build.ros2.org/job/Gdev__rosbag2_storage_mcap__ubuntu_focal_amd64/7/#showFailuresLink

**Comment by jtbandes** [comment] 2022-04-20 20:22
Failure output:

```
13:17:09 4: Test command: /usr/bin/python3 "-u" "/opt/ros/galactic/share/ament_cmake_test/cmake/run_test.py" "/tmp/ws/test_results/rosbag2_storage_mcap/cpplint.xunit.xml" "--package-name" "rosbag2_storage_mcap" "--output-file" "/tmp/ws/build_isolated/rosbag2_storage_mcap/ament_cpplint/cpplint.txt" "--command" "/opt/ros/galactic/bin/ament_cpplint" "--xunit-file" "/tmp/ws/test_results/rosbag2_storage_mcap/cpplint.xunit.xml"
13:17:09 4: Test timeout computed to be: 120
13:17:09 4: -- run_test.py: invoking following command in '/tmp/ws/src/rosbag2_storage_mcap/rosbag2_storage_mcap':
13:17:09 4:  - /opt/ros/galactic/bin/ament_cpplint --xunit-file /tmp/ws/test_results/rosbag2_storage_mcap/cpplint.xunit.xml
13:17:09 4: Using '--root=/tmp/ws/src/rosbag2_storage_mcap/rosbag2_storage_mcap/src' argument
13:17:09 4: 
13:17:09 4: /tmp/ws/src/rosbag2_storage_mcap/rosbag2_storage_mcap/src/mcap_storage.cpp:404:  Add #include <algorithm> for max  [build/include_what_you_use] [4]
13:17:09 4: Done processing /tmp/ws/src/rosbag2_storage_mcap/rosbag2_storage_mcap/src/mcap_storage.cpp
13:17:09 4: 
13:17:09 4: /tmp/ws/src/rosbag2_storage_mcap/rosbag2_storage_mcap/src/message_definition_cache.cpp:85:  Add #include <string> for string  [build/include_what_you_use] [4]
13:17:09 4: /tmp/ws/src/rosbag2_storage_mcap/rosbag2_storage_mcap/src/message_definition_cache.cpp:84:  Add #include <unordered_set> for unordered_set<>  [build/include_what_you_use] [4]
13:17:09 4: /tmp/ws/src/rosbag2_storage_mcap/rosbag2_storage_mcap/src/message_definition_cache.cpp:39:  Add #include <set> for set<>  [build/include_what_you_use] [4]
13:17:09 4: Done processing /tmp/ws/src/rosbag2_storage_mcap/rosbag2_storage_mcap/src/message_definition_cache.cpp
13:17:09 4: 
13:17:09 4: /tmp/ws/src/rosbag2_storage_mcap/rosbag2_storage_mcap/src/message_definition_cache.hpp:0:  No #ifndef header guard found, suggested CPP variable is: MESSAGE_DEFINITION_CACHE_HPP_  [build/header_guard] [5]
13:17:09 4: Done processing /tmp/ws/src/rosbag2_storage_mcap/rosbag2_storage_mcap/src/message_definition_cache.hpp
13:17:09 4: 
13:17:09 4: Category 'build/header_guard' errors found: 1
13:17:09 4: Category 'build/include_what_you_use' errors found: 4
13:17:09 4: Total errors found: 5
13:17:09 4: -- run_test.py: return code 1
13:17:09 4: -- run_test.py: verify result file '/tmp/ws/test_results/rosbag2_storage_mcap/cpplint.xunit.xml'
13:17:09 4/6 Test #4: cpplint ..........................***Failed    0.33 sec
```

**Comment by jtbandes** [comment] 2022-04-20 20:25
Note that [message_definition_cache.hpp](https://github.com/ros-tooling/rosbag2_storage_mcap/blob/main/rosbag2_storage_mcap/src/message_definition_cache.hpp) ***does*** have `#pragma once`, as well as includes for `string`, `unordered_set`, and `set`.

**Comment by clalancette** [comment] 2022-04-20 20:29
> Note that [message_definition_cache.hpp](https://github.com/ros-tooling/rosbag2_storage_mcap/blob/main/rosbag2_storage_mcap/src/message_definition_cache.hpp) _**does**_ have `#pragma once`, as well as includes for `string`, `unordered_set`, and `set`.

The problem is that the linters don't understand `#pragma once`, since it is non-standard.  For better or worse, the ROS 2 standard is to use the `#ifdef` guards in a particular style.

As for the includes, include-what-you-use generally means you include everything you need, even in the `.cpp` files.  That way if you change the associated header file, the C++ file can still compile.  This is arguably a subjective complaint, but it is also the style ROS 2 uses.

**Comment by jtbandes** [comment] 2022-04-20 20:34
Thanks for the input. One thing I don't understand is why we didn't see these errors in this repo's CI using `action-ros-ci` but only saw them on the build farm?

**Comment by jtbandes** [comment] 2022-04-20 20:35
I did find this relevant sentence in the google c++ style guide:

> Do not rely on transitive inclusions. This allows people to remove no-longer-needed #include statements from their headers without breaking clients. This also applies to related headers - foo.cc should include bar.h if it uses a symbol from it even if foo.h includes bar.h.

**Comment by jtbandes** [comment] 2022-04-20 20:55
Fixed in https://github.com/ros-tooling/rosbag2_storage_mcap/commit/e9ba96f8c4d7168b9d99b1dcd4483ba956bf800d

**Closed as completed by jtbandes** 2022-04-20 20:55 UTC
Labels: bug

**Comment by clalancette** [comment] 2022-04-20 21:01
> Thanks for the input. One thing I don't understand is why we didn't see these errors in this repo's CI using `action-ros-ci` but only saw them on the build farm?

Hm, that is a good question.  One possible reason is that the action-ros-ci actions use Ubuntu Jammy images (which is what Rolling/Humble use), while the Gdev on the buildfarm is for Galactic, and will therefore use Ubuntu Focal.  If would be interesting to see if the Rdev jobs show the same problem.
