### ISSUE TITLE
Transient-local topics are not repeated into individual MCAP files when file splitting is enabled

### ISSUE THREAD

**Issue by jhurliman** [ros-tooling/rosbag2_storage_mcap#75] opened 2022-11-11 19:42 UTC
## Description
Transient-local topics are not repeated into individual MCAP files when file splitting is enabled

### Expected Behavior
Transient-local topics are repeated into individual MCAP files when file splitting is enabled

### Actual Behavior
Transient-local topics are not repeated into individual MCAP files when file splitting is enabled

## To Reproduce
** Steps to reproduce the behavior, e.g.
1. Record a transient-local topic with file splitting enabled

## System (please complete the following information)
 - OS: All
 - ROS 2 Distro: All

**Comment by MichaelOrlov** [comment] 2022-11-12 01:57
@jhurliman This is not a bug. This is a feature and we do this on purpose. See my detailed explanation here https://github.com/ros2/rosbag2/pull/1051#pullrequestreview-1059614100

**Comment by amacneil** [comment] 2022-11-13 22:34
Related ticket in rosbag2: https://github.com/ros2/rosbag2/issues/1159

**Comment by james-rms** [comment] 2022-11-29 03:47
Closing in favor of https://github.com/ros2/rosbag2/issues/1159

**Closed as completed by james-rms** 2022-11-29 03:47 UTC
Labels: bug
