### ISSUE TITLE
Error on MCAP file play on Galactic

### ISSUE THREAD

**Issue by bertaveira** [ros-tooling/rosbag2_storage_mcap#52] opened 2022-09-03 15:52 UTC
## Description
When trying to play a mcap file on Galactic it fails. Files that in the past worked with previous versions of this plugin.

### Actual Behavior
In ARM64 platforms it gives this error:
```
/usr/bin/python3: symbol lookup error: /opt/ros/galactic/lib/aarch64-linux-gnu/libmcap.so: undefined symbol: LZ4F_createDecompressionContext
```

In x86 the error is different:
```
[ERROR] [1662220057.345135680] [rosbag2_storage]: Could not load/open plugin with storage id 'mcap'.
[ERROR] [1662220057.345184113] [rosbag2_transport]: Failed to play: No storage could be initialized. Abort
```

## To Reproduce
```
ros2 bag play -s mcap file_name.mcap
```

## System (please complete the following information)
 - OS: Ubuntu 20.04
 - ROS 2 Distro: Galactic

**Comment by jtbandes** [comment] 2022-09-03 15:59
Duplicate of #45. Fix will be out in the next galactic sync.

**Closed as not planned by jtbandes** 2022-09-03 15:59 UTC
Labels: bug
