### ISSUE TITLE
Humble: Unable to find storage id "mcap"

### ISSUE THREAD

**Issue by bertaveira** [ros-tooling/rosbag2_storage_mcap#85] opened 2022-11-26 15:31 UTC
## Description
I was getting a segmentation fault when playing mcap using the CLI command. I was in the last sync so I decided to update all packages to the recent one. 

Since then I have been getting this error. If I do `ros2 pkg list` I can see it there. Also tried purging it and installing it again but with no success.

<img width="875" alt="image" src="https://user-images.githubusercontent.com/9644729/204096536-646756a1-8440-4c7c-a94b-615b2cd8e4c5.png">

## System (please complete the following information)
 - OS: Ubuntu 22.04
 - ROS 2 Distro: Humble

**Comment by bertaveira** [comment] 2022-11-26 15:40
Duplicate of #82 but maybe the name of that issue is not inclusive enough since it seems to happen in multiple ROS2 Distros

**Comment by james-rms** [comment] 2022-11-29 03:46
Duplicate of #82

**Closed as completed by james-rms** 2022-11-29 03:46 UTC
Labels: bug
